/**
 * @fileoverview OpenAPI docs for /api/v1/ticktick
 */

export const ticktickDocs = {
  '/api/v1/ticktick/auth': {
    get: {
      tags: ['Auth'],
      summary: 'Start TickTick OAuth flow',
      description: `
Starts OAuth by redirecting the browser to TickTick authorization.

### Frontend usage
1. Frontend/extension generates its redirect URI
2. Frontend opens this endpoint in a browser tab or popup
3. Backend responds with HTTP 302 to TickTick
4. TickTick later redirects back to \`/api/v1/ticktick/callback\`

### Important
This endpoint returns a redirect on success, not JSON.
      `.trim(),
      parameters: [
        {
          name: 'redirect_uri',
          in: 'query',
          required: true,
          description:
            "Frontend redirect URI. For Chrome extensions this is usually obtained via chrome.identity.getRedirectURL('ticktick').",
          schema: {
            type: 'string',
            example: 'https://<extension-id>.chromiumapp.org/ticktick',
          },
        },
      ],
      responses: {
        302: {
          description: 'Redirects browser to TickTick authorization page.',
          headers: {
            Location: {
              description:
                "TickTick authorization URL with client_id, redirect_uri, and encoded state.",
              schema: {
                type: 'string',
                example:
                  'https://ticktick.com/oauth/authorize?client_id=...&response_type=code&state=...',
              },
            },
          },
        },
        400: {
          description: 'Missing redirect_uri.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                status: 'error',
                message: 'Missing extension redirect_uri',
              },
            },
          },
        },
        429: {
          description: 'Too many auth attempts.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                status: 'error',
                message:
                  'Too many authentication attempts, please try again later.',
                retryAfter: '15 minutes',
              },
            },
          },
        },
      },
    },
  },

  '/api/v1/ticktick/callback': {
    get: {
      tags: ['Auth'],
      summary: 'Handle TickTick OAuth callback',
      description: `
Receives the authorization code from TickTick and completes sign-in.

### What happens here
1. Backend validates \`code\` and \`state\`
2. Exchanges code for TickTick access/refresh tokens
3. Resolves or creates app user
4. Redirects browser back to frontend with \`?userId=<...>\`

### Frontend usage
Frontend does not call this manually in normal flow.
Frontend only needs to read the final redirected URL and extract \`userId\`.

### Important
Success returns HTTP 302 redirect, not JSON.
      `.trim(),
      parameters: [
        {
          name: 'code',
          in: 'query',
          required: true,
          description: 'Authorization code from TickTick.',
          schema: { type: 'string', example: 'abc123authcode' },
        },
        {
          name: 'state',
          in: 'query',
          required: true,
          description:
            'Opaque encoded state generated by the backend during /auth.',
          schema: {
            type: 'string',
            example: 'eyJleHRlbnNpb25SZWRpcmVjdFVyaSI6Imh0dHBzOi8vLi4uIn0=',
          },
        },
      ],
      responses: {
        302: {
          description: 'Redirects back to frontend redirect_uri with userId.',
          headers: {
            Location: {
              description:
                'Frontend redirect URI with resolved userId appended.',
              schema: {
                type: 'string',
                example:
                  'https://<extension-id>.chromiumapp.org/ticktick?userId=USER_4a9f2c1b3e7d8a0f',
              },
            },
          },
        },
        400: {
          description: 'Missing code or state.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                status: 'error',
                message: 'Missing code or state',
              },
            },
          },
        },
        429: {
          description: 'Auth rate limit exceeded.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                status: 'error',
                message:
                  'Too many authentication attempts, please try again later.',
              },
            },
          },
        },
        500: {
          description: 'Token exchange or database upsert failed.',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                status: 'error',
                message: 'Token exchange failed: invalid_grant',
              },
            },
          },
        },
      },
    },
  },
};